### ISSUE TITLE
Spotify 100% CPU Usage

### ISSUE THREAD

**Issue by dahjelle** [paulyoung/Statusfy#20]
I fully realize this is _probably_ not a Statusfy issue proper, but just in case: Spotify seems to regularly start eating up a full CPU core when I have Statusfy running. It doesn't happen all the time, and I haven't been able to nail down a reproducible set of steps; however, it doesn't seem to happen when I'm not using Statusfy.

As I said, I suspect it is an implementation issue within Spotify itself, but I thought I'd mention it here in case anyone had ideas.

Thanks for your work on Statusfy! :-D

**Comment by paulyoung** [comment]
Statusfy _does_ frequently make requests to Spotify in order to display the relevant information.

Perhaps that would account for what you're seeing but I don't know why it would happen intermittently.

I'm also not sure how I would address it if that was the case, except maybe to request information less often.

**Comment by sidewinder12s** [comment]
I'd say this is probably not an issue with Statusfy and can probably close this issue.

**Comment by z3t0** [comment]
I haven't noticed this issue myself, it usually stays at about 2% of CPU usage.
